dubbo:
  registries:
    nacos:
      protocol: nacos
      timeout: 5s
      group: dev
      address: 127.0.0.1:8848
    zk:
      protocol: zk
      timeout: 5s
      group: dev
      address: 193.168.56.100:2181
  services:
    helloService:
      interface: org.dubbo.service.HelloService
      registry: nacos,zk
    orderService:
      interface: org.dubbo.service.OrderService
      registry: nacos